/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sparkbwa_BwaJni */

#ifndef _Included_com_github_sparkbwa_BwaJni
#define _Included_com_github_sparkbwa_BwaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_sparkbwa_BwaJni
 * Method:    bwa_jni
 * Signature: (I[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_github_sparkbwa_BwaJni_bwa_1jni
  (JNIEnv *, jobject, jint, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
